description: >
  NexPloit CLI is a Command Line Interface (CLI) tool for Bright's solutions.
  You can use NexPloit CLI for full control over scans such as: initialize, stop, poll, maintain and more.
  In addition, NexPloit CLI can serve as a Repeater to scan local targets, without exposing them to the internet.
docker:
  - image: 'neuralegion/repeater'
parameters:
  tag:
    default: latest
    description: >
      Name of the tag to use for the image.
      https://hub.docker.com/r/neuralegion/repeater
    type: string
